using System.Net.Http.Headers;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace AzLogs.Ingestion.WeatherApiClient;

/// <summary>
/// Auto-generated National Weather Service API client
/// </summary>
/// <remarks>
/// The main body of this class is generated by NSwag at build time, based on the openapi.yaml snippet here.
/// 
/// This partial implementation adds the user agent header to the request, which is required by the service.
/// </remarks>
public partial class WeatherClient
{
    partial void PrepareRequest(HttpClient client, System.Net.Http.HttpRequestMessage request, string url)
    {
        request.Headers.UserAgent.Add(ProductInfoHeaderValue.Parse("Weather.Worker/0.0.0"));
    }
}
